#!/usr/bin/env bash
[[ -v VERBOSE ]] && set -x

#shellcheck enable=check-set-e-suppressed
set -eu
shopt -s inherit_errexit

excludes=()
includes=()
ignores=()
tmp_args=()

read_to_tmp() {
    local input_file="$1"
    local opt="${2:-}"

    if [[ ! -r "${input_file}" ]]; then
        echo "File \"${input_file}\" does not exist or is not readable!"
        exit 2
    fi

    tmp_args=()
    while read -r row; do
        row=${row#[[:space:]]}
        if [[ -n "${row}" ]]; then
            if [[ -n "${opt}" ]]; then
                tmp_args+=("${opt}" "${row}")
            else
                tmp_args+=("${row}")
            fi
        fi
    done < "${input_file}"
}

while (( $# > 0 )); do
    case "$1" in
        --include)
            includes+=("$2")
            shift 2
            ;;
        --exclude)
            excludes+=("$2")
            shift 2
            ;;
        --ignore)
            ignores+=(-e "$2")
            shift 2
            ;;
        --include-file)
            read_to_tmp "$2"
            includes+=("${tmp_args[@]}")
            shift 2
            ;;
        --exclude-file)
            read_to_tmp "$2"
            excludes+=("${tmp_args[@]}")
            shift 2
            ;;
        --ignore-file)
            read_to_tmp "$2" "-e"
            ignores+=("${tmp_args[@]}")
            shift 2
            ;;
        *)
            break
            ;;
    esac
done

print_join() { local IFS="$1"; shift; echo "$*"; }

shopt -s globstar
GLOBIGNORE="$(print_join ":" "${excludes[@]}")"
export GLOBIGNORE

# disable SC2068, we need globbing here
# shellcheck disable=SC2068
if shellcheck "${ignores[@]}" --format gcc ${includes[@]} ; then
    echo "No issues found!"
else
    exit $?
fi
