---
'on':
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
  schedule:
    - cron: "0 1 * * 0" # Run every Sunday at 1:00 UTC
defaults:
  run:
    shell: 'bash'
env:
  IMAGE_NAME: 'ghcr.io/dsiebel/shellcheck-docker:latest'
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Get git commit timestamps'
        id: 'metadata'
        run: |
          echo "commit_timestamp=$(git log -1 --pretty=%ct)" | tee -a "${GITHUB_OUTPUTS}"

      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@v3'

      - name: 'Build'
        uses: 'docker/build-push-action@v6'
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE_NAME}}
        env:
          SOURCE_DATE_EPOCH: '${{ steps.metadata.outputs.git_commit_timestamp }}'
