---
name: 'Docker'
'on':
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
  schedule:
    - cron: "0 1 * * 0" # Run every Sunday at 1:00 UTC
defaults:
  run:
    shell: 'bash'
env:
  IMAGE_NAME: 'ghcr.io/dsiebel/shellcheck-docker:latest'
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:

      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@v3'

      - name: 'Build'
        uses: 'docker/build-push-action@v6'
        env:
          DOCKER_BUILD_RECORD_UPLOAD: 'false'
        with:
          push: "${{ github.event_name != 'pull_request' }}"
          load: "${{ github.event_name == 'pull_request' }}"
          tags: "${{ env.IMAGE_NAME}}"

      - name: 'Test'
        run: |
          docker run --rm --entrypoint shellcheck "${{ env.IMAGE_NAME}}" --version

          docker run --rm \
            --workdir /usr/local/bin \
            --env VERBOSE=1 \
            "${{ env.IMAGE_NAME}}" \
            --include shellcheckw
